/**
 * PDF-form ingest adapter — the "computer-typed" channel for radio answers.
 *
 * The scannable answer sheets carry interactive AcroForm radio groups, one
 * per response field, each named by the field's scorer key (see
 * `src/lib/omr-sheet.ts`). When someone fills the PDF on a computer instead
 * of printing it, the answers are already structured data: this reads those
 * radio selections straight back — no image, no fiducials, no recognition.
 *
 * It returns the SAME `OmrReadResult` the scan reader produces (keyed by
 * scorer key, with identical blank/required-field warnings via the shared
 * `assembleRow`), so both channels feed one confirmation UI and one scorer.
 * There is no flattened image (`warped`) because nothing was scanned.
 */
import { PDFDocument, PDFRadioGroup, PDFTextField } from 'pdf-lib';
import type { OmrTemplate } from '../../assessments/omr/types';
import type { FieldRead, OmrReadResult } from './types';
import { assembleRow } from './reader';

const fail = (error: string): OmrReadResult => ({
  ok: false,
  error,
  response: {},
  fields: [],
  warnings: [],
  attention: [],
});

/**
 * Pull the stamped form id out of a sheet's PDF Keywords, if our marker is
 * present. Sheets generated by `generateAnswerSheet` carry `form:<id>`;
 * anything else (a results report, a foreign PDF, an older sheet) returns null,
 * so the caller only rejects on a *positive* id mismatch and never on absence.
 */
function embeddedFormId(doc: PDFDocument): string | null {
  const match = doc.getKeywords()?.match(/form:([\w-]+)/);
  return match ? match[1] : null;
}

/**
 * Read the radio (and free-text) fields of one sheet against `template`, from
 * an already-loaded document.
 *
 * `prefix` is the field namespace the sheet was drawn under: empty for a lone
 * sheet, or `t<i>_` for one sheet within a combined "all tests" document (see
 * `generateCombinedAnswerSheets`). Field names are matched against the prefix
 * and stripped of it, so the returned `response`/`text` are always keyed by the
 * bare scorer keys the survey and scorer expect — one sheet reads identically
 * whether it stands alone or is embedded in a combined form.
 */
function readFormFields(
  doc: PDFDocument,
  template: OmrTemplate,
  prefix: string,
): OmrReadResult {
  // Index this sheet's radio groups by bare key, and collect its free-text
  // fields (name/date/comments). When reading a lone sheet (no prefix), skip
  // any namespaced fields so a combined document can't leak in; when reading a
  // namespace, take only the fields under it. A PDF with no AcroForm yields an
  // empty field list here rather than throwing.
  const groups = new Map<string, PDFRadioGroup>();
  const text: Record<string, string> = {};
  for (const field of doc.getForm().getFields()) {
    const name = field.getName();
    if (prefix ? !name.startsWith(prefix) : /^t\d+_/.test(name)) continue;
    const key = prefix ? name.slice(prefix.length) : name;
    if (field instanceof PDFRadioGroup) {
      groups.set(key, field);
    } else if (field instanceof PDFTextField) {
      const value = field.getText()?.trim();
      if (value) text[key] = value;
    }
  }
  if (groups.size === 0) {
    return fail(
      'This PDF has no answer fields to read — it looks like a results report, ' +
        'not the answer sheet. Upload the answer sheet you downloaded ' +
        '("Download test"), filled in on-screen or scanned from print.',
    );
  }

  const response: Record<string, number> = {};
  const fields: FieldRead[] = [];
  const warnings: string[] = [];
  const attention: string[] = [];
  let anySelected = false;

  for (const section of template.sections) {
    for (const row of section.rows) {
      const reads: FieldRead[] = row.fields.map((field): FieldRead => {
        const selected = groups.get(field.key)?.getSelected();
        // Map the selected export value back to its bubble value, so we honor
        // whatever the template encoded rather than assuming a plain integer.
        const bubble =
          selected != null ? field.bubbles.find((b) => String(b.value) === selected) : undefined;
        const value = bubble ? bubble.value : null;
        if (value !== null) anySelected = true;
        // A radio group holds at most one selection, so a filled field is
        // unambiguous and a missing one is simply blank — never 'ambiguous'.
        return {
          key: field.key,
          value,
          darknesses: [],
          confidence: value !== null ? 1 : 0,
          status: value !== null ? 'ok' : 'blank',
        };
      });
      for (const r of reads) fields.push(r);
      assembleRow(row.label, reads, response, warnings, attention);
    }
  }

  if (!anySelected) {
    return fail(
      `This ${template.title} answer sheet has no answers filled in yet. Fill in ` +
        'the bubbles on a computer and save the PDF, then upload it — or upload a ' +
        'photo/scan.',
    );
  }

  return {
    ok: true,
    response,
    fields,
    warnings,
    attention,
    text: Object.keys(text).length ? text : undefined,
  };
}

/**
 * Read a filled interactive answer-sheet PDF against its template.
 *
 * DOM-free (pdf-lib runs in Node), so the round trip generate → fill → read
 * is unit-testable headlessly.
 */
export async function readPdfForm(
  bytes: Uint8Array | ArrayBuffer,
  template: OmrTemplate,
): Promise<OmrReadResult> {
  let doc: PDFDocument;
  try {
    doc = await PDFDocument.load(bytes);
  } catch {
    return fail('That file is not a readable PDF.');
  }

  // Reject a sheet built for a different assessment before parsing any answers.
  // Only a positive id mismatch rejects; sheets without the marker fall through
  // to the field-level guards below, so an older download still reads normally.
  const formId = embeddedFormId(doc);
  if (formId && formId !== template.id) {
    return fail(
      `This is the answer sheet for a different assessment (form ${formId}), but ` +
        `you're entering a result for ${template.title}. Upload the ${template.title} ` +
        `answer sheet, or start from that assessment's card.`,
    );
  }

  return readFormFields(doc, template, '');
}

/** Convenience: read a filled interactive PDF straight from a File/Blob. */
export async function readPdfFormFromBlob(
  blob: Blob,
  template: OmrTemplate,
): Promise<OmrReadResult> {
  return readPdfForm(await blob.arrayBuffer(), template);
}

/** One assessment's read within a combined "all tests" document. */
export interface CombinedChildRead {
  /** `OmrTemplate.id` of the assessment this read belongs to. */
  templateId: string;
  /** The field namespace it was read from (`t<i>_`, or `''` for a lone sheet). */
  prefix: string;
  /** Zero-based index of the page this sheet's fields sit on, so the review UI
   *  can open the combined PDF straight to it (`#page=<page + 1>`). */
  page: number;
  /** The read itself — always `ok: true` in a successful combined result. */
  result: OmrReadResult;
}

export type CombinedReadResult =
  | { ok: true; children: CombinedChildRead[] }
  | { ok: false; error: string };

/** First scorer key a template exposes — enough to fingerprint which
 *  assessment a field namespace holds when a combined PDF lacks the manifest. */
function firstFieldKey(template: OmrTemplate): string {
  return template.sections[0]?.rows[0]?.fields[0]?.key ?? '';
}

/** Find the template whose fields are present under `prefix`, by fingerprint. */
function templateByKeys(
  groupNames: Set<string>,
  templates: OmrTemplate[],
  prefix: string,
): OmrTemplate | undefined {
  return templates.find((t) => groupNames.has(prefix + firstFieldKey(t)));
}

/**
 * Parse the combined-document manifest from PDF Keywords: `omr-combined` plus
 * one `t<i>:<template-id>` per embedded sheet (see `generateCombinedAnswerSheets`).
 * Returns `[]` for any document without the marker, so an older combined PDF —
 * or a lone sheet — falls through to fingerprint detection instead.
 */
function parseCombinedManifest(doc: PDFDocument): { prefix: string; id: string }[] {
  const keywords = doc.getKeywords() ?? '';
  if (!/\bomr-combined\b/.test(keywords)) return [];
  const out: { prefix: string; id: string }[] = [];
  const re = /\bt(\d+):([\w-]+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(keywords))) out.push({ prefix: `t${m[1]}_`, id: m[2] });
  return out;
}

/** Distinct `t<i>_` field namespaces present in a document, for manifest-less
 *  combined PDFs (downloaded before the manifest was stamped). */
function discoverPrefixes(groupNames: Set<string>): string[] {
  const prefixes = new Set<string>();
  for (const name of groupNames) {
    const m = name.match(/^(t\d+_)/);
    if (m) prefixes.add(m[1]);
  }
  return [...prefixes];
}

/**
 * Zero-based page index a sheet's fields live on, found by following one of its
 * radio widgets to its page. Lets the review UI open the combined PDF at the
 * right sheet instead of always page 1. Falls back to 0 if the widget or its
 * page can't be resolved.
 */
function pageIndexOf(doc: PDFDocument, template: OmrTemplate, prefix: string): number {
  const name = prefix + firstFieldKey(template);
  const field = doc.getForm().getFields().find((f) => f.getName() === name);
  if (!(field instanceof PDFRadioGroup)) return 0;
  const widget = field.acroField.getWidgets()[0];
  const pageRef = widget?.P();
  if (!pageRef) return 0;
  const idx = doc.getPages().findIndex((p) => p.ref === pageRef);
  return idx >= 0 ? idx : 0;
}

/**
 * Read a completed-tests PDF and split it into one result per assessment it
 * contains, against the supplied `templates` (the candidate child assessments).
 *
 * Handles three shapes with one entry point, so a professional can upload
 * whatever a patient sends: the combined "all tests" document (all four, via
 * the stamped manifest), a combined document holding any subset, or even a lone
 * single-assessment sheet. Blank sheets are silently dropped, so only the
 * assessments that were actually filled come back — the rest stay open for
 * another input method.
 */
export async function readCombinedPdfForm(
  bytes: Uint8Array | ArrayBuffer,
  templates: OmrTemplate[],
): Promise<CombinedReadResult> {
  let doc: PDFDocument;
  try {
    doc = await PDFDocument.load(bytes);
  } catch {
    return { ok: false, error: 'That file is not a readable PDF.' };
  }

  const groupNames = new Set<string>();
  for (const field of doc.getForm().getFields()) {
    if (field instanceof PDFRadioGroup) groupNames.add(field.getName());
  }
  if (groupNames.size === 0) {
    return {
      ok: false,
      error:
        'This PDF has no answer fields to read — it looks like a results report, ' +
        'not a completed answer sheet. Upload the tests you downloaded, filled in ' +
        'on-screen or scanned from print.',
    };
  }

  // Resolve which (namespace, template) pairs to read: the stamped manifest
  // first, then namespace fingerprinting for a manifest-less combined PDF, and
  // finally a lone sheet identified by its form id or field fingerprint.
  const entries: { prefix: string; template: OmrTemplate }[] = [];
  const manifest = parseCombinedManifest(doc);
  if (manifest.length) {
    for (const m of manifest) {
      const template = templates.find((t) => t.id === m.id);
      if (template) entries.push({ prefix: m.prefix, template });
    }
  } else {
    const prefixes = discoverPrefixes(groupNames);
    if (prefixes.length) {
      for (const prefix of prefixes) {
        const template = templateByKeys(groupNames, templates, prefix);
        if (template) entries.push({ prefix, template });
      }
    } else {
      const formId = embeddedFormId(doc);
      const template =
        (formId ? templates.find((t) => t.id === formId) : undefined) ??
        templateByKeys(groupNames, templates, '');
      if (template) entries.push({ prefix: '', template });
    }
  }

  if (entries.length === 0) {
    return {
      ok: false,
      error:
        "We couldn't match this PDF to any of the assessments. Upload the completed " +
        'tests you downloaded here, or enter a single assessment from its own card.',
    };
  }

  const children: CombinedChildRead[] = entries
    .map((e) => ({
      templateId: e.template.id,
      prefix: e.prefix,
      page: pageIndexOf(doc, e.template, e.prefix),
      result: readFormFields(doc, e.template, e.prefix),
    }))
    // Keep only the sheets that carry answers; a blank one reads as "not filled"
    // and is simply left for another input method (partial uploads are fine).
    .filter((c) => c.result.ok);

  if (children.length === 0) {
    return {
      ok: false,
      error:
        'None of the sheets in this PDF have answers filled in yet. Fill them in ' +
        'on a computer and save, then upload — or upload a photo/scan per test.',
    };
  }

  return { ok: true, children };
}

/** Convenience: read a completed-tests PDF straight from a File/Blob. */
export async function readCombinedPdfFormFromBlob(
  blob: Blob,
  templates: OmrTemplate[],
): Promise<CombinedReadResult> {
  return readCombinedPdfForm(await blob.arrayBuffer(), templates);
}
